
export type SiteTokenDanceRechargeCopy = typeof siteTokenDanceRechargeCopy.zh;

export const siteTokenDanceRechargeCopy = {
  zh: {
    home: "返回首页",
    sidebar: "账户中心",
    membership: "会员套餐",
    pointsRecharge: "积分充值",
    tokenDanceCredits: "TokenDance 额度",
    signOut: "退出登录",
    signIn: "登录后充值",
    signedOutState: "未登录",
    signedOutTitle: "登录后即可查看和补充额度",
    eyebrow: "TokenDance 额度中心",
    title: "TokenDance 额度",
    intro: "查看当前可用额度，需要时输入金额完成充值。支付确认后，到账额度会自动更新。",
    currentAccount: "当前账号",
    availableCredits: "可用额度",
    totalReceived: "累计获得",
    totalUsed: "累计使用",
    creditsUnit: "额度",
    perRequest: "当前每次使用",
    perRequestSuffix: "额度 / 次",
    refresh: "刷新",
    refreshed: "额度已更新",
    unavailable: "TokenDance 额度服务暂时不可用，请稍后再试。",
    rechargeTitle: "充值额度",
    rechargeIntro: "输入整数金额，先查看本次实际支付和到账额度，再确认付款。",
    amountLabel: "充值金额",
    amountSuffix: "元",
    amountPlaceholder: "请输入整数金额",
    amountHint: "到账额度以确认页显示的结果为准。",
    previewQuote: "查看到账额度",
    previewingQuote: "正在计算",
    offerFallback: "按当前活动规则计算",
    offerRuleHint: "活动优惠作用于每次使用时的额度扣减；本次到账额度以当前报价为准。",
    offerEnds: "活动截止",
    quoteTitle: "确认本次充值",
    quoteDescription: "确认金额和到账额度后再前往支付。",
    actualPayment: "实际支付",
    creditsArriving: "到账额度",
    quoteExpires: "报价有效至",
    confirmPayment: "确认并前往支付",
    creatingOrder: "正在准备支付",
    paymentTitle: "完成充值",
    paymentDescription: "使用微信扫码，或在手机上打开支付页。",
    scanTitle: "微信扫码支付",
    openPayment: "在手机上打开支付页",
    paymentPending: "等待支付确认",
    paymentPendingBody: "支付完成后请保留本页，额度会自动到账。",
    paymentPaid: "充值成功",
    paymentPaidBody: "到账额度已经加入当前账户。",
    paymentExpired: "支付已失效",
    paymentExpiredBody: "请关闭窗口后重新发起充值。",
    paymentFailed: "暂时未能完成充值",
    paymentFailedBody: "这笔订单没有到账，请稍后重新发起。",
    paymentManualReview: "订单正在核对",
    paymentManualReviewBody: "暂时不用重复支付，核对完成后会更新额度。",
    orderNumber: "订单号",
    recentOrders: "最近充值",
    emptyOrders: "还没有 TokenDance 充值记录",
    amount: "支付金额",
    credits: "到账额度",
    status: "状态",
    time: "时间",
    statusMap: {
      creating: "准备中",
      pending: "待支付",
      paid: "已到账",
      expired: "已失效",
      failed: "未完成",
      closed: "已关闭",
      manual_review: "核对中",
    } as Record<string, string>,
    errors: {
      site_auth_session_missing: "登录状态已失效，请重新登录后继续。",
      auth_session_required: "登录状态已失效，请重新登录后继续。",
      site_billing_origin_invalid: "当前页面无法发起充值，请刷新后重试。",
      tokendance_managed_recharge_unavailable: "TokenDance 额度暂时不可用，请稍后再试。",
      tokendance_managed_recharge_amount_invalid: "请输入页面允许范围内的整数金额。",
      tokendance_recharge_amount_invalid: "请输入页面允许范围内的整数金额。",
      tokendance_recharge_quote_invalid: "这份到账结果不可用，请重新确认金额。",
      tokendance_recharge_quote_expired: "这份到账结果已失效，请重新确认金额。",
      tokendance_recharge_quote_not_found: "没有找到这份到账结果，请重新确认金额。",
      tokendance_recharge_quote_consumed: "这份到账结果已经创建过订单，请查看最近充值。",
      tokendance_recharge_idempotency_key_invalid: "暂时未能创建订单，请重新确认金额。",
      tokendance_recharge_idempotency_conflict: "当前订单状态已变化，请刷新后查看。",
      tokendance_recharge_order_invalid: "这笔充值订单暂时不可用，请重新发起。",
      tokendance_recharge_order_not_found: "没有找到这笔充值订单。",
      tokendance_recharge_order_missing: "没有找到这笔充值订单。",
      tokendance_recharge_external_session_invalid: "暂时未能打开支付，请重新发起充值。",
      tokendance_managed_unavailable: "TokenDance 额度暂时不可用，请稍后再试。",
      site_billing_http_502: "充值服务暂时不可用，请稍后再试。",
      fallback: "暂时未能完成操作，请稍后再试。",
    } as Record<string, string>,
  },
  en: {
    home: "Back to home",
    sidebar: "Account center",
    membership: "Membership plans",
    pointsRecharge: "Points recharge",
    tokenDanceCredits: "TokenDance credits",
    signOut: "Sign out",
    signIn: "Sign in to recharge",
    signedOutState: "Signed out",
    signedOutTitle: "Sign in to review and add credits",
    eyebrow: "TokenDance credit center",
    title: "TokenDance credits",
    intro: "Review your available credits and enter an amount whenever you need more. Your balance updates automatically after payment is confirmed.",
    currentAccount: "Current account",
    availableCredits: "Available credits",
    totalReceived: "Total received",
    totalUsed: "Total used",
    creditsUnit: "credits",
    perRequest: "Current usage",
    perRequestSuffix: "credits / request",
    refresh: "Refresh",
    refreshed: "Credits updated",
    unavailable: "TokenDance credits are temporarily unavailable. Please try again later.",
    rechargeTitle: "Recharge credits",
    rechargeIntro: "Enter a whole-number amount, review the actual payment and arriving credits, then confirm payment.",
    amountLabel: "Recharge amount",
    amountSuffix: "CNY",
    amountPlaceholder: "Enter a whole-number amount",
    amountHint: "The confirmation screen is the source of truth for arriving credits.",
    previewQuote: "Review arriving credits",
    previewingQuote: "Calculating",
    offerFallback: "Calculated with the current offer",
    offerRuleHint: "The offer reduces credits used per request. Credits arriving are always taken from this quote.",
    offerEnds: "Offer ends",
    quoteTitle: "Confirm this recharge",
    quoteDescription: "Review the amount and arriving credits before paying.",
    actualPayment: "Actual payment",
    creditsArriving: "Credits arriving",
    quoteExpires: "Quote valid until",
    confirmPayment: "Confirm and continue to payment",
    creatingOrder: "Preparing payment",
    paymentTitle: "Complete recharge",
    paymentDescription: "Scan with WeChat or open the payment page on your phone.",
    scanTitle: "Scan with WeChat",
    openPayment: "Open payment page on mobile",
    paymentPending: "Waiting for payment",
    paymentPendingBody: "Keep this page open after paying. Your credits will arrive automatically.",
    paymentPaid: "Recharge successful",
    paymentPaidBody: "The arriving credits are now available in your account.",
    paymentExpired: "Payment expired",
    paymentExpiredBody: "Close this window and start a new recharge.",
    paymentFailed: "Recharge was not completed",
    paymentFailedBody: "No credits arrived for this order. Please start again later.",
    paymentManualReview: "Order under review",
    paymentManualReviewBody: "Do not pay again. Your credits will update when the review is complete.",
    orderNumber: "Order number",
    recentOrders: "Recent recharges",
    emptyOrders: "No TokenDance recharge orders yet",
    amount: "Payment",
    credits: "Credits arriving",
    status: "Status",
    time: "Time",
    statusMap: {
      creating: "Preparing",
      pending: "Pending",
      paid: "Arrived",
      expired: "Expired",
      failed: "Incomplete",
      closed: "Closed",
      manual_review: "Under review",
    } as Record<string, string>,
    errors: {
      site_auth_session_missing: "Your sign-in has expired. Sign in again to continue.",
      auth_session_required: "Your sign-in has expired. Sign in again to continue.",
      site_billing_origin_invalid: "This page cannot start a recharge. Refresh and try again.",
      tokendance_managed_recharge_unavailable: "TokenDance credits are temporarily unavailable. Please try again later.",
      tokendance_managed_recharge_amount_invalid: "Enter a whole-number amount within the allowed range.",
      tokendance_recharge_amount_invalid: "Enter a whole-number amount within the allowed range.",
      tokendance_recharge_quote_invalid: "This credit quote is unavailable. Review the amount again.",
      tokendance_recharge_quote_expired: "This credit quote expired. Review the amount again.",
      tokendance_recharge_quote_not_found: "This credit quote is no longer available. Review the amount again.",
      tokendance_recharge_quote_consumed: "This quote already created an order. Review recent recharges.",
      tokendance_recharge_idempotency_key_invalid: "The order could not be created. Review the amount again.",
      tokendance_recharge_idempotency_conflict: "The order changed. Refresh to review its latest status.",
      tokendance_recharge_order_invalid: "This recharge order is unavailable. Start a new recharge.",
      tokendance_recharge_order_not_found: "This recharge order could not be found.",
      tokendance_recharge_order_missing: "This recharge order could not be found.",
      tokendance_recharge_external_session_invalid: "The payment page could not be opened. Start the recharge again.",
      tokendance_managed_unavailable: "TokenDance credits are temporarily unavailable. Please try again later.",
      site_billing_http_502: "The recharge service is temporarily unavailable. Please try again later.",
      fallback: "This action could not be completed. Please try again later.",
    } as Record<string, string>,
  },
};
